server {
    listen 80;
    server_name 10.23.88.131;
    root /var/www/p2;
    index inventario.php;

    location = / {
        return 302 /inventario.php;
    }

    location = /inventario.php {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location / {
        return 404;
    }
}
