server {
    listen 80;
    server_name 10.23.88.130;
    root /var/www/p2;
    index caja.php;

    location = / {
        return 302 /caja.php;
    }

    location = /caja.php {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location / {
        return 404;
    }
}
